SELECT B.USER_ID AS USER_ID
     , B.NICKNAME AS NICKNAME
     , SUM(A.PRICE) AS TOTAL_SALES
  FROM USED_GOODS_BOARD A
 INNER JOIN USED_GOODS_USER B
    ON A.WRITER_ID = B.USER_ID
 WHERE A.STATUS = 'DONE'
 GROUP BY USER_ID
        , NICKNAME
   HAVING SUM(PRICE) >= 700000
 ORDER BY TOTAL_SALES ASC